version: '3.0'

services:
   nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx_lb.conf
      - ./certs/:/etc/letsencrypt/live/joict.nl/
    ports:
      - 80:80
      - 443:443
