version: '3.3'
networks:
  # network for App <-> DB transactions
  mm-in:
    driver: overlay
    internal: true
  # this network faces the outside world
  mm-out:
    driver: overlay
    internal: false
volumes:
  mm-dbdata:
  traefik-certs:
services:
  web:
  # use official traefik image
    image: traefik
    ports:
      - "80:80"
      # you can view the traefik's dashboard in http://localhost:8080
      - "8080:8080"
      - "443:443"
    networks:
      - mm-out
    command: >
      --acme
      --acme.email="j.j.dejosselindejong@gmail.com"
      --acme.entrypoint=https --acme.onhostrule
      --acme.storage="acme/certs.json"
      --acme.acmelogging
      --web
      --docker
      --docker.domain=docker.localhost
      --docker.swarmmode
      --docker.watch
      --logLevel=DEBUG
    volumes:
      # traefik needs the docker socket in order to work properly
      - /var/run/docker.sock:/var/run/docker.sock
      # no traefik config file is being used
      # you can deep further in the traefik docs
      # http://docs.traefik.io/user-guide/examples/
      - /dev/null:/traefik.toml
      # use a named-volume for certs persistency
      - traefik-certs:/acme
    deploy:
      restart_policy:
       condition: on-failure
