{%- set websites = pillar.get('websites') %}
version: '3.0'

services:
  #  {{ websites['git']['backend_name'] }}:
  #   image: 'gitlab/gitlab-ce:latest'
  #   restart: always
  #   hostname: 'git.joict.nl'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://git.joict.nl'
  #       letsencrypt['enable'] = false
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #     - '2222:2222'

  #  nginx:
  #   image: nginx:latest
  #   depends_on:
  #      - {{ websites['git']['backend_name'] }}
  #   volumes:
  #     - /root/compose/large_compose/nginx.conf:/etc/nginx/conf.d/nginx_lb.conf
  #     - /root/compose/large_compose/certs/:/etc/letsencrypt/live/joict.nl/
  #   ports:
  #     - 80:80
  #     - 443:443

  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker --docker.swarmMode --docker.watch  --constraint=node.role==manager --docker.domain=traefik --network traefik-net # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"    # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
      - "443:443"
    volumes:
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

